### ISSUE TITLE
Calling find_face method on alpha fails with Server Error

### ISSUE THREAD

**Issue by tesYolan** [singnet/face-services#22]
Hello, 

To integrate some of my services with your face-detect and face-landmark detection, I was querying your agent at `0x4cBe33Aa28eBBbFAa7d98Fa1c65af2FEf6885EF2` with some of the images that I test my services with and stumbled on the following error when i make the following call on the image below

`snet client call find_face request_face`

where request_face is a file that has the following format `{"image": "image_64", algorithm: "dlib_cnn"}` so as to pass the large string64 to snet-cli

![test image](https://cdn.rawgit.com/singnet/emotion-recognition-service/59c2d816/turtles.png)

The error i get is
```
<-- {"jsonrpc": "2.0", "error": {"code": -32000, "message": "Server error"}, "id": 1} (500 Internal Server Error)
Traceback (most recent call last):
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/bin/snet", line 11, in <module>
    sys.exit(main())
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/snet_cli/__init__.py", line 16, in main
    getattr(args.cmd(conf, args), args.fn)()
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/snet_cli/commands.py", line 430, in call
    job_address=job_address, job_signature=job_signature, **params)
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/jsonrpcclient/__init__.py", line 11, in request
    return HTTPClient(endpoint).request(method, *args, **kwargs)
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/jsonrpcclient/client.py", line 171, in send
    return self._send_message(request, **kwargs)
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/jsonrpcclient/http_client.py", line 82, in _send_message
    log_format='<-- %(message)s (%(http_code)s %(http_reason)s)')
  File "/home/tesfa/anaconda3/envs/emotion-recogntion-snet-agent/lib/python3.6/site-packages/jsonrpcclient/client.py", line 114, in _process_response
    response['error'].get('data'))
jsonrpcclient.exceptions.ReceivedErrorResponse: Server error
```

FYI, I have tested your service on the images on your test directory, your service provides the appropriate responses.

**Comment by ferrouswheel** [comment]
Doh, I was looking at the grpc server. The json-rpc endpoints were not dropping the alpha channel. Fixed now, container rebuilt and deployed.
